// <auto-generated />
namespace InsightClub.Creator.Bot.Migrations

open System
open InsightClub.Creator.Bot
open Microsoft.EntityFrameworkCore
open Microsoft.EntityFrameworkCore.Infrastructure

[<DbContext(typeof<Context.Context>)>]
type ContextModelSnapshot() =
  inherit ModelSnapshot()

  override this.BuildModel(modelBuilder: ModelBuilder) =
    modelBuilder

      .UseIdentityByDefaultColumns()
      .HasAnnotation("Relational:MaxIdentifierLength", 63)
      .HasAnnotation("ProductVersion", "5.0.9")
    |> ignore

    modelBuilder.Entity(
      "InsightClub.Creator.Bot.Model+Block",
      (fun b ->

        b
          .Property<int>("CourseId")
          .IsRequired(true)
          .HasColumnType("integer")
        |> ignore

        b
          .Property<int>("BlockIndex")
          .IsRequired(true)
          .HasColumnType("integer")
        |> ignore

        b
          .Property<string>("BlockType")
          .IsRequired(true)
          .HasColumnType("text")
        |> ignore

        b
          .Property<string>("Content")
          .IsRequired(true)
          .IsUnicode(true)
          .HasColumnType("text")
        |> ignore

        b.HasKey("CourseId", "BlockIndex") |> ignore

        b.ToTable("Blocks") |> ignore

        )
    )
    |> ignore

    modelBuilder.Entity(
      "InsightClub.Creator.Bot.Model+Course",
      (fun b ->

        b
          .Property<int>("CourseId")
          .IsRequired(true)
          .ValueGeneratedOnAdd()
          .HasColumnType("integer")
          .UseIdentityByDefaultColumn()
        |> ignore

        b
          .Property<string>("CourseDescription")
          .IsRequired(true)
          .IsUnicode(true)
          .HasColumnType("text")
        |> ignore

        b
          .Property<string>("CourseName")
          .IsRequired(true)
          .IsUnicode(true)
          .HasColumnType("text")
        |> ignore

        b
          .Property<int>("CreatorId")
          .IsRequired(true)
          .HasColumnType("integer")
        |> ignore

        b.HasKey("CourseId") |> ignore


        b.HasIndex("CreatorId", "CourseName").IsUnique()
        |> ignore

        b.ToTable("Courses") |> ignore

        )
    )
    |> ignore

    modelBuilder.Entity(
      "InsightClub.Creator.Bot.Model+Creator",
      (fun b ->

        b
          .Property<int>("CreatorId")
          .IsRequired(true)
          .ValueGeneratedOnAdd()
          .HasColumnType("integer")
          .UseIdentityByDefaultColumn()
        |> ignore

        b
          .Property<string>("BotState")
          .IsRequired(true)
          .HasColumnType("jsonb")
        |> ignore

        b
          .Property<Int64>("TelegramId")
          .IsRequired(true)
          .HasColumnType("bigint")
        |> ignore

        b.HasKey("CreatorId") |> ignore


        b.HasIndex("TelegramId").IsUnique() |> ignore

        b.ToTable("Creators") |> ignore

        )
    )
    |> ignore

    modelBuilder.Entity(
      "InsightClub.Creator.Bot.Model+Block",
      (fun b ->
        b
          .HasOne("InsightClub.Creator.Bot.Model+Course", null)
          .WithMany()
          .HasForeignKey("CourseId")
          .OnDelete(DeleteBehavior.Cascade)
          .IsRequired()
        |> ignore)
    )
    |> ignore

    modelBuilder.Entity(
      "InsightClub.Creator.Bot.Model+Course",
      (fun b ->
        b
          .HasOne("InsightClub.Creator.Bot.Model+Creator", null)
          .WithMany()
          .HasForeignKey("CreatorId")
          .OnDelete(DeleteBehavior.Cascade)
          .IsRequired()
        |> ignore)
    )
    |> ignore
